# Site settings
title: Luu Gia Thuy
name: Luu Gia Thuy
email: luugiathuy@gmail.com
baseurl: ""
url: http://luugiathuy.com
description: my coding journal
twitter_username: luugiathuy
github_username: luugiathuy

# Build settings
markdown: rdiscount
permalink: /:year/:month/:title/
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

exclude:
  - README.md
