# Site settings
title: Luu Gia Thuy
email: luugiathuy@gmail.com
description: "my coding journal"
baseurl: ""
url: "http://luugiathuy.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
