# Site settings
title: Luu Gia Thuy
name: Luu Gia Thuy
email: luugiathuy@gmail.com
baseurl: ""
url: http://luugiathuy.com
description: My name is Luu Gia Thuy. I am from Vietnam. I'm passionate about software engineer, mobile application, programming language and best practices of code.
twitter_username: luugiathuy
github_username: luugiathuy

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: compressed
gems:
  - jekyll-sitemap
exclude:
  - README.md
