# Site settings
title: Luu Gia Thuy
email: luugiathuy@gmail.com
description: "my coding journal"
baseurl: ""
url: "http://luugiathuy.com"
twitter_username: luugiathuy
github_username:  luugiathuy

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
